### ISSUE TITLE
Separate entry point for generating pipelines vs. executing pipelines

### ISSUE THREAD

**Issue by bjschoenfeld** [byu-dml/d3m-experimenter#3]
`ExperimenterDriver` is the only entry point and it does both pipeline generation and pipeline execution. We should have a way to just generate pipelines and just execute pipelines. Each could probably have a separate command line interface.

**Comment by orionw** [comment]
Each has a separate command line interface.  High levels details are in the README and low level details are in the files that use them (experimenter.py and experimenter_driver.py)
