### ISSUE TITLE
Add Proper Datatype Encoding To All Pipelines

### ISSUE THREAD

**Issue by epeters3** [byu-dml/d3m-experimenter#48]
As requested by Brandon, we'd like to include ordinal encoding (the `"d3m.primitives.data_transformation.ordinal_encoder.SKlearn"` primitive) followed by one hot encoding of categorical variables (the `"d3m.primitives.data_transformation.one_hot_encoder.SKlearn"` primitive) as part of the common pre-processing on all pipelines generated by the experimenter.

Is `experimenter.experimenter.Experimenter._add_initial_steps` the only method that needs to be altered for this? That will need to be verified.

Here is a [JSON example](https://gitlab.com/datadrivendiscovery/primitives/blob/master/v2019.6.7/JPL/d3m.primitives.data_transformation.ordinal_encoder.SKlearn/2019.6.7/pipelines/952b1163-98e5-400e-84e4-5ae3b4b58acd.json#L143-178) of using the `"d3m.primitives.data_transformation.ordinal_encoder.SKlearn"` primitive.

Here is a [JSON example](https://gitlab.com/datadrivendiscovery/primitives/blob/master/v2019.6.7/JPL/d3m.primitives.data_transformation.one_hot_encoder.SKlearn/2019.6.7/pipelines/68973a0f-8c55-40cb-b059-2eb0c04eacb1.json#L143-178) of using the `"d3m.primitives.data_transformation.one_hot_encoder.SKlearn"` primitive.

I would recommend starting this issue from the branch referenced in #46. That has some logic that makes it so step references are no longer hard coded, and should allow you to add those primitive steps more easily.

**Comment by epeters3** [comment]
Hi @erikhuck, like we talked about yesterday with Brandon, we'd love to have you help out on the D3M Experimenter. I'd love to have you try to work on this issue if that's ok. Once this issue is completed, Orion will be able to re-run the experimenter so we can re-create our meta-data set, only this time including the pipeline steps mentioned in this issue, and using the newest version of D3M. Feel free to ask questions, and thank you!

**Comment by bjschoenfeld** [comment]
I only requested categorical encoding, but ordinal would be good too. The more we can use the semantic labels on each column to correctly preprocess the data, the better.

**Comment by epeters3** [comment]
It looks like OrdinalEncoder is the option sklearn offers for both categorical and ordinal encoding, so maybe we get ordinal encoding for free, which is nice. They have a LabelEncoder, but apparently that is designed for single target columns. See https://datascience.stackexchange.com/questions/39317/difference-between-ordinalencoder-and-labelencoder.

**Comment by bjschoenfeld** [comment]
That link is a good clarification. Does the D3M wrapping preserve those same semantics?

**Comment by epeters3** [comment]
However, it looks like the D3M wrapped version of LabelEncoder does [generalize to do a full dataframe](https://gitlab.com/datadrivendiscovery/sklearn-wrap/blob/devel/primitives/SKLabelEncoder.py#L108). I'm not sure how to check if the D3M wrapping of OrdinalEncoder has those same semantics you talk about. I think the code for it is auto-generated. I'm assuming it does have the same semantics since its just a wrapper.

**Comment by epeters3** [comment]
BTW @erikhuck it looks like by default, sklearn's ordinal encoders and one hot encoders will encode all columns, not just categorical ones, so you may need to check on that to make sure the D3M primitives are encoding what they should and not what they shouldn't.

**Comment by epeters3** [comment]
From what I can tell @bjschoenfeld, it doesn't look like sklearn's OrdinalEncoder actually includes any ordinality in the encoding by default. It seems to just be a label encoder that encodes every column.

**Comment by bjschoenfeld** [comment]
Let's find a way to encode just the categorical and ordinal data (if possible), keeping the numeric data as is. Note that some numeric data may be in the for of ints, e.g. counts of things, but I am not sure if that is ordinal or not.

**Comment by epeters3** [comment]
FYI, the sklearn's OneHotEncoder can go straight from categorical to one hot encoded data, so it may not need any intermediate ordinal or label encoding to happen before the one hot encoding.

**Comment by epeters3** [comment]
After our conversation, this is what we would like to have accomplished in this issue:
- Encode all ordinal data with the ordinal encoder
- Encode all categorical data with the one hot encoder

**Comment by epeters3** [comment]
Resolved by PR #72.
