### ISSUE TITLE
Rerun Current Experiments

### ISSUE THREAD

**Issue by epeters3** [byu-dml/d3m-experimenter#49]
Requires #48 to be completed first.

Now that we have the D3M version updated, and once #48 is completed, we'll have everything we need to rerun the current experiment setup (straight pipelines and ensembles) and populate the Mongo DB with it.

_Note_: We will also add functionality later (see #38) for copying those pipeline runs and pipelines to the D3M MtL DB.

**Comment by epeters3** [comment]
Brandon has also asked that before we kick of the experiments, to update him on what changes have been made; what experiments will be run.

**Comment by bjschoenfeld** [comment]
I would also like us to do #59 before we run things.

**Comment by epeters3** [comment]
As discussed, it would be great to do a dry run of this, even before #48 is finished, if Orion has time.

**Comment by epeters3** [comment]
This rerun of the experiments has begun. We have 300,000+ pipeline runs in the D3M DB to date. All the straight pipelines have been completed and saved (except the ones that errored out for timeout issues or other), and many of the width 3 ensemble pipelines have completed.
