### ISSUE TITLE
Refactor to point experimenter to external database

### ISSUE THREAD

**Issue by bjschoenfeld** [byu-dml/d3m-experimenter#5]
Currently, we create a mongodb instance along with the experimenter. With #4, we can now refactor so that the experimenter receives an environment variable with the database hostname and port.

**Comment by orionw** [comment]
Database hostname and port are implemented and stored outside of git.  Database has been tested for persistence and does persist.

**Comment by bjschoenfeld** [comment]
https://github.com/byu-dml/d3m-experimenter/blob/04ef4da49e5842f2a2abf2c7bc6c808a33a7747d/experimenter/database_communication.py#L6

This is a good start. Let's use a `config.yml` file or environment variables. Then we can have generic code which reads in the configuration and errs if it cannot find it.
