### ISSUE TITLE
Search The Pipeline Architecture Space

### ISSUE THREAD

**Issue by epeters3** [byu-dml/d3m-experimenter#51]
We would like to add support for doing a random or genetic algorithm approach (see TPOT for inspiration) for searching the pipeline architecture space, to improve the variety of the DAG structures in our meta-dataset.

**Comment by bjschoenfeld** [comment]
@orionw Could we use our genetic tuning package to do this? We would have to specify a JSON configuration that could be sampled/mutated to make a new pipeline.

This is one of the questions I have had for a long time: how do we enumerate the space of possible pipelines?

**Comment by epeters3** [comment]
**One simple idea** that has some faults that could be addressed, but does benefit from being simple, is to search the architecture space by iteratively adding random nodes and edges.

For example, starting with a basic common data cleansing pipeline (value imputation, label encoding, etc.), we could then do this:

```
for each step in some random range of integers:
    1) randomly select a primitive to add to the pipeline
    2) randomly select the output of some primitive already in the pipeline
    3) add the primitive to the pipeline, using the randomly selected output as its input.
       This has the effect of adding a random node and edge to the pipeline DAG.
    4) add the output of that newly added primitive to the pool of possible primitive
       outputs to consider for the next iteration. 
```

One laissez faire way we could potentially temper the wackiness of the pipelines this approach might create is to include some kind of fitness feedback, so the approach tries to make pipelines that perform well. When an approach has to evaluate models intermittently though, it becomes much slower at generating pipelines.

**Comment by orionw** [comment]
I don't think the `configtune` package would be a good fit for this.  I also think we're miscommunicating on what we mean by "genetically search."  Usually you use a genetic search to optimize something, but this needs to be more of a random walk (unless we want to specifically optimize the pipelines we create - but in that case the genetic algorithm wouldn't necessarily mutate the pipelines for us, especially the `configtune` package.  We'd really have to carefully design the schema being mutated to use `configtune` and I don't see an easy way for it to do DAGS).

@epeters3's idea is more along the lines of things I think we're looking for.  If we want a truly random one, his would work great.  **Another idea** would be to create a class that follows rules like "this classifier has to be proceeded by a one-hot encoder" etc.  It could randomly split (with a max splitting length and/or max primitive amount) and the probabilistically come back together (with more weight towards coming back the longer/more primitives are in the pipeline).  This would make it more "typical" of pipeline branching and less random (since Evan's idea would be truly random and create some interesting bizarre pipelines - which may be what we're looking for).  We just need to decide which path we want to go down and we can start creating a class for it.

**Comment by epeters3** [comment]
**Another potential way**, inspired by a project Steven did last semester on neuron architecture search, is similar to my random idea above but preserves a little more structure in that all primitives have edges back to the final node(s) in the graph:

```
1) Start with a basic straight pipeline
2) for each step in some randomly sized range:
    3) randomly choose to add an edge or a node
    4) if edge:
        5) randomly choose two nodes in the graph
        6) create an edge between the two nodes
    7) if node:
        8) randomly choose an edge in the graph
        9) insert a node within that edge, so the two nodes that edge
           connected are now connected via the new node in the middle
```
Here again the nodes are primitives and the edges are directed output/input streams from a primitive to primitive.

In this approach, there would need to be some checking when randomly selecting a node pair to see if the primitives are compatible enough to use the output from the first as the input to the second. When randomly selecting an edge as well, the primitive selected would need to be a good candidate for being inserted within that edge.

**Comment by epeters3** [comment]
The topic of Neural Architecture Search (NAS) has a lot in common with what we're doing here. Here's a March 2019 [NAS survey paper](https://arxiv.org/abs/1808.05377) published by JMLR. Maybe we could find some inspiration in there. We may not be trying to optimize like NAS is, but the paper still discusses search spaces and search strategies.

**Comment by epeters3** [comment]
**Another potential option** is to use some D3M TA2 system, and let it create pipelines for us. Seems like this would work well if the TA2 creates pipelines of diverse architectures.

**Comment by epeters3** [comment]
Another idea is to let some D3M TA2 create pipelines for us, if we know that TA2 is good at creating diverse architectures. I'm less crazy about that idea, because we already have TA2 pipelines in the D3M MtL DB we could use. Maybe that's an idea.

**Comment by epeters3** [comment]
In any approach we do, we could consider primitive motifs (pipeline sections) as well as or instead of individual primitives, so we always have some useful structures in our pipelines.

**Comment by epeters3** [comment]
After our team meeting today, we decided on the approach of generating random pipelines within a rectangular structure. This is the high-level approach:

![Image from iOS](https://user-images.githubusercontent.com/21148260/65354232-3d406900-dbac-11e9-93aa-cb2b1ca363cf.jpg)

1. Make `n` pipeline structures made up of placeholder primitives. This is done as follow:
    1. Decide on a pipeline `depth`, `max_width`, and `max_num_inputs`.
    1. Starting with the common data pre-processing pipeline, for each layer until `depth` is reached:
        1. Sample a `layer_width` from `[1,max_width]`
        1. Add `layer_width` placeholder primitives to the layer
        1. For each primitive in the layer:
            1. Sample `num_inputs` from `[1,min(num_prev_nodes, max_num_inputs)]`.
            1. Randomly select `num_inputs` previous nodes and route their output as the primitive's input.
    1. Perform cleanup, where the output of all terminal nodes is routed to a final primitive, then to the construct predictions primitive.
1. In order to support batching for the deep meta-models, take the `n` structures and fill in `b` copies of them, each with random primitives, ensuring that the last one before the construct predictions primitive is a classifier. We will restrict primtives used to sklearn pre-processors and classifiers.

We will also want to record meta-data fields on each pipeline generated by this approach that record the pipeline's `depth`, `max_width`, and `max_num_inputs`.

Another potential addition is to include a constraint on the sum of `depth`, `max_width`, and `max_num_inputs`, so that each pipeline is kept within a desireable minimum and maximum complexity. This would allow things like `depth=1, max_width=12, max_num_inputs=1`, etc, which would be interesting.
