### ISSUE TITLE
Clean Up The CLI

### ISSUE THREAD

**Issue by epeters3** [byu-dml/d3m-experimenter#52]
The command line interface for this repo needs some love, as described in #41. It would be great to clean up the CLI-specific code, to make it more modular, organized, and extensible.

_Note_: This issue can be addressed in stages i.e. in multiple PRs if that makes things easier.

**Comment by bjschoenfeld** [comment]
> This issue can be addressed in stages

Perhaps having multiple issues would help as well. I like where you are headed!

**Comment by epeters3** [comment]
It seems like for this issue, it would suffice just to refactor the `main` function and `ExperimenterDriver` class inside `experimenter_driver.py` to:

1. support running the ensemble experiments
2. eliminate any duplicate code
3. simplify logic where its reasonably feasible to do so

Given this slightly simplified scope, is this something you might have time to tackle @orionw?
