### ISSUE TITLE
Use public D3M image

### ISSUE THREAD

**Issue by bjschoenfeld** [byu-dml/d3m-experimenter#54]
Using public images will mean that we don't have to get D3M credentials for everyone working on this. They are available here: https://gitlab.com/datadrivendiscovery/images

I think this is the correct image, but am not sure: `registry.gitlab.com/datadrivendiscovery/images/primitives:ubuntu-bionic-python36-v2019.6.7`

**Comment by epeters3** [comment]
Updating this should include updating the container reference url in the `Dockerfile`, and removing the login credentials from `.travis-ci.yml` and from the Travis web app too.
