### ISSUE TITLE
Enable running of a single test

### ISSUE THREAD

**Issue by bjschoenfeld** [byu-dml/d3m-experimenter#69]
Developing is much easier if you can run just a single test at a time, instead of the whole test suite. This can be done typically by calling:

`python3 ./path/to/test_case.py TestCaseClass.test_method_name`. 

For some reason, this does not work in this repo.

**Comment by epeters3** [comment]
Brandon I have been using `python3 -m unittest test_dir.specific_test_module.SpecificTestClass.specific_test_method` and that has been working for me.

**Comment by epeters3** [comment]
I haven't tried your way yet.

**Comment by bjschoenfeld** [comment]
If that works, then we should be fine. We just need to train everyone to use that.

**Comment by epeters3** [comment]
Thanks, I'll close this issue for now. Feel free to reopen it whenever there is an issue!
